  InboundHTTPNetworkAclEntry:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref MyDefaultNetworkAcl
      RuleNumber: '${ASUX::NACLRuleNumber}'     ### '100'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'   ### Whether this rule applies to egress traffic from the subnet (true) or ingress traffic to the subnet (false). By default, AWS CloudFormation specifies false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '80'
        To: '80'

#EOF