  OutBoundResponsePortsAclEntryFor${ASUX::WhichNACLRef}:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref ${ASUX::WhichNACLRef}  ### !Ref MyDefaultNetworkAcl
      RuleNumber: '${ASUX::NACLRuleNumber}'     ### '220'
      Protocol: '6'
      RuleAction: allow
      Egress: 'true'  ### Whether this rule applies to egress traffic from the subnet (true) or ingress traffic to the subnet (false). By default, AWS CloudFormation specifies false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '1024'
        To: '65535'

#EOF