  ${ASUX::MyEC2InstanceName}:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          StandupOnly:
            - Standup
          StandUpInstallAndRun:
            - Standup
            - Services
### Per AWS Support CASE 6213287331: these 'empty' config will CAUSE problems for cfn-init (when run thru UserData)
            # - Install
            # - Configure
            # - Upload
        Standup:
### Per AWS Support CASE 6213287331: these 'empty' config will CAUSE problems for cfn-init (when run thru UserData)
        # Install: []   
        # Configure: []
        # Services:  ### This will be populated by   ${ASUX::AWSCFN.HOME}/myjobs/Svcs-ASUX.org-DEV-1.yaml
        # Upload: []


# Complete!
# + yum install -y aws-cfn-bootstrap
# Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
# Package aws-cfn-bootstrap-1.4-31.amzn2.noarch already installed and latest version
# Nothing to do
# + /opt/aws/bin/cfn-init -v --stack org-ASUX-Playground-Tokyo-simple-EC2-OrgASUXplayEC2plain --resource OrgASUXplayEC2plain --configsets Standup --region ap-northeast-1
# Error occurred during build: 'list' object has no attribute 'get'
# Jul 01 03:51:05 cloud-init[3348]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
# Jul 01 03:51:05 cloud-init[3348]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
# Jul 01 03:51:05 cloud-init[3348]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
# Cloud-init v. 18.2-72.amzn2.0.7 finished at Mon, 01 Jul 2019 03:51:05 +0000. Datasource DataSourceEc2.  Up 28.81 seconds


#EOF