  MyInternetGateway:
    Description: >-
      REMEMBER: an IGW is associated with entire VPC.  Only NATs are associated
      with a single public-subnet.
    Type: 'AWS::EC2::InternetGateway'
    Properties:
    DependsOn:
      - MyPublicSubnetAZ1
      - MyPublicSubnetAZ2
      - MyPublicSubnetAZ3

#EOF