  MyInternetGateway:
    Description: >-
      REMEMBER: an IGW is associated with entire VPC.  Only NATs are associated
      with a single public-subnet.
    Type: 'AWS::EC2::InternetGateway'
    Properties:

    ### Since I'm creating VPCs and Subnets independently.. since I'm creating IGW __WITHIN__ the CFN-template for a VPC.. I cannot have the following dependencies
    # DependsOn:
    #   - MyPublicSubnetAZ1
    #   - MyPublicSubnetAZ2
    #   - MyPublicSubnetAZ3

#EOF