  MyVPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    DependsOn:
      - MyInternetGateway
    Properties:
      VpcId: !Ref ${ASUX::MyVPCName}
      InternetGatewayId: !Ref MyInternetGateway

#EOF