  ${AWS::XWKACLInboundEntryLabel}:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref {AWS::MyDefaultNetworkAcl}
      RuleNumber: '{AWS::XWKACLInboundRuleNum}'
      Protocol: '{AWS::XWKACLProtocol}'
      RuleAction: allow
      Egress: 'false'   ### Whether this rule applies to egress traffic from the subnet (true) or ingress traffic to the subnet (false). By default, AWS CloudFormation specifies false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '{AWS::InboundFromPortRange}'
        To: '{AWS::InboundToPortRange}'

#EOF