  ${AWS::XWKACLInboundEntryLabel}:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref {AWS::MyDefaultNetworkAcl}
      RuleNumber: '{AWS::XWKACLInboundRuleNum}'
      Protocol: '{AWS::XWKACLProtocol}'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '{AWS::InboundFromPortRange}'
        To: '{AWS::InboundToPortRange}'

#EOF