Parameters:
  OrgName:
    Description: "What is the Organization a.k.a. the prefix for the stack?  Example: orgASUX"
    Type: String
    Default: orgASUX
  Environment:
    Description: "What environment is this? For, TAG Name=ENV"
    Type: String
    Default: Playground

  MyStackNamePrefix:
    Description: No Default-value!  Typically it's something like "${MyOrgName}-${MyEnvironment}-${MyAWSRegion}"
    Type: String
    Default: ${ASUX::OrgName}-${ASUX::Environment}-${ASUX::AWSRegion}

  EC2getsPublicIPByDefault:
    Description: Whether any EC2 instance created within this VPC automatically gets a PUBLIC-IP (accessible via internet)
    Type: String
    Default: 'false'

#EOF
