  My${ASUX::Scope}SubnetNetworkAclAssociation${ASUX::foreach.index+1}:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Condition: doesExistSubnet${ASUX::foreach.index+1}
    Properties:
      SubnetId: !Ref My${ASUX::Scope}SubnetAZ${ASUX::foreach.index+1}
      NetworkAclId: !ImportValue ${ASUX::MyVPCStackPrefix}-${ASUX::Scope}NetworkAclID
      # NetworkAclId: !GetAtt
      #   - !ImportValue ${ASUX::MyVPCName}
      #   - ${ASUX::Scope}NetworkAcl

#EOF
