  MyPrivateSubnetRouteTableAssociationAZ${ASUX::foreach.index+1}:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Condition: doesExistSubnet${ASUX::foreach.index+1}
    Properties:
      SubnetId: !Ref MyPrivateSubnetAZ${ASUX::foreach.index+1}
      RouteTableId: !ImportValue
        Ref: MyPrivateRouteTable

#EOF