  SG${ASUX::Scope}:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG${ASUX::ItemNumber} to allow access to port ${ASUX::Scope} in the environment SG${ASUX::MyEnvironment}
      VpcId: !ImportValue 
        Ref: MyVPC
##      VpcId: !ImportValue: !Sub "${MyOrgName}-${MyEnvironment}-${AWS::Region}-${AWS::StackName}"
##      VpcId: !ImportValue   ## You can't use the short form of !ImportValue when it contains a !Sub. The following example is valid for AWS CloudFormation, but not valid for YAML:
##        !Sub "${MyOrgName}-SydneyVPC-VPCID"
##      VpcId: !ImportValue "OrgASUX-SydneyVPC-VPCID"
      SecurityGroupIngress:    ## to allow NO Protocol (a.k.a. No internet-traffic at all): IpProtocol: "-1"
      - IpProtocol: tcp
        FromPort: ${ASUX::SG-Inbound-Port}  ### Note: These ASUX-variables will be defined in a PROPERTIES File called: ${ASUX::CURRENTWORKINGDIRECTORY}/${ASUX::JobSetName}/tmp/SG-attributes-${ASUX::Scope}-${ASUX::ItemNumber}.properties
        ToPort: ${ASUX::SG-Inbound-Port}    ### Note: These ASUX-variables will be defined in a PROPERTIES File called: ${ASUX::CURRENTWORKINGDIRECTORY}/${ASUX::JobSetName}/tmp/SG-attributes-${ASUX::Scope}-${ASUX::ItemNumber}.properties
        CidrIp: ${ASUX::SG-Inbound-CIDRRange} ### 0.0.0.0/0
      SecurityGroupEgress:    ## to allow NO Protocol (a.k.a. No internet-traffic at all): IpProtocol: "-1"
      - IpProtocol: -1
##        FromPort: -1    ## An ICMP type number of -1 indicates a wildcard (i.e., any ICMP type number).
##        ToPort: -1      ## An ICMP type number of -1 indicates a wildcard (i.e., any ICMP type number).
        CidrIp: 0.0.0.0/0 ### THIS iS STATIC/Fixed: Let's Not offer too many bells-n-whistles.  Not a bad idea to connect to any external source, especially since most other APPS/SERVICES are on the defacto-internet called AWS/Azure)

### EOF
