  SGSSH${ASUX::Environment}${ASUX::SGUniqueName}:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access to a Linux EC2 instance hosting org.ASUX components
      VpcId: !ImportValue 
        Ref: MyVPC
##      VpcId: !ImportValue: !Sub "${MyOrgName}-${MyEnvironment}-${AWS::Region}-${AWS::StackName}"
##      VpcId: !ImportValue   ## You can't use the short form of !ImportValue when it contains a !Sub. The following example is valid for AWS CloudFormation, but not valid for YAML:
##        !Sub "${MyOrgName}-SydneyVPC-VPCID"
##      VpcId: !ImportValue "OrgASUX-SydneyVPC-VPCID"
      SecurityGroupIngress:    ## to allow NO Protocol (a.k.a. No internet-traffic at all): IpProtocol: "-1"
      - IpProtocol: tcp
        FromPort: 2049
        ToPort: 2049
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:    ## to allow NO Protocol (a.k.a. No internet-traffic at all): IpProtocol: "-1"
      - IpProtocol: -1
##        FromPort: -1    ## An ICMP type number of -1 indicates a wildcard (i.e., any ICMP type number).
##        ToPort: -1      ## An ICMP type number of -1 indicates a wildcard (i.e., any ICMP type number).
        CidrIp: 0.0.0.0/0

### EOF
