aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-vpc.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-VPC --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-sg-ssh-0.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-ssh-2layer-0-SG --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-sg-https-1.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-https-2layer-1-SG --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-sg-5432-2.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-5432-2layer-2-SG --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-subnet-PublicWithNATGW-0.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-PublicWithNATGW-2layer-0-Subnet --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-ec2plain-MyWebASUXLinux1.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-2layer-EC2-MyWebASUXLinux1 --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-subnet-Private-1.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-Private-2layer-1-Subnet --region us-east-1
aws s3 cp --profile ${AWSprofile} /Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/fullstack-ec2plain-MyPrivASUXLinux2.yaml   s3://org-asux-aws-cfn/org-ASUX-Playground-Ohio-2layer-EC2-MyPrivASUXLinux2 --region us-east-1
aws cloudformation create-stack --profile ${AWSprofile} --stack-name org-ASUX-Playground-Ohio-2layer --region us-east-2 --template-body file:///Users/Sarma/Documents/Development/src/org.ASUX/AWS/CFN/test/myjobs/2layer/stackset.yaml
